version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2404:2024.11.1
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Dagger CLI
          command: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sudo -E sh; cd -; }
      - run:
          name: Run QA Pipeline
          command: dagger -c '. FIRECRAWL_API_KEY GITHUB_TOKEN | do-qa' --progress=plain